package com.gft.hellorobobar;

// Generated by Selenium IDE

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class RoboBarSuitTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @BeforeAll
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @AfterAll
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void totalCarrito() {
        // Test name: TotalCarritoColas
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("http://localhost:3000/");
        // 2 | setWindowSize | 973x1095 |
        driver.manage().window().setSize(new Dimension(973, 1095));
        // 3 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click();
        // 4 | assertText | css=tr:nth-child(4) > .ng-binding | €1.25
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText(), is("€1.25"));
        // 5 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click();
        // 6 | assertText | css=tr:nth-child(4) > .ng-binding | €2.50
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText(), is("€2.50"));
        // 7 | click | css=.ng-scope:nth-child(1) > td .input-group-prepend > .btn |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-prepend > .btn")).click();
        // 8 | click | css=.ng-scope:nth-child(1) > td .input-group-prepend > .btn |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-prepend > .btn")).click();
        // 9 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click();
        // 10 | assertText | css=tr:nth-child(4) > .ng-binding | €2.00
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText(), is("€2.00"));
        // 11 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click();
        // 12 | assertText | css=tr:nth-child(4) > .ng-binding | €4.00
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText(), is("€4.00"));
        // 13 | click | css=.ng-scope:nth-child(2) > td .input-group-prepend > .btn |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-prepend > .btn")).click();
        // 14 | click | css=.ng-scope:nth-child(2) > td .input-group-prepend > .btn |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-prepend > .btn")).click();
        // 15 | click | css=.ng-scope:nth-child(3) .input-group-append > .btn |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(3) .input-group-append > .btn")).click();
        // 16 | assertText | css=tr:nth-child(4) > .ng-binding | €3.00
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText(), is("€3.00"));
        // 17 | click | css=.ng-scope:nth-child(3) .input-group-append > .btn |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(3) .input-group-append > .btn")).click();
        // 18 | assertText | css=tr:nth-child(4) > .ng-binding | €6.00
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText(), is("€6.00"));
        // 19 | click | css=.ng-scope:nth-child(3) .input-group-prepend > .btn |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(3) .input-group-prepend > .btn")).click();
        // 20 | click | css=.ng-scope:nth-child(3) .input-group-prepend > .btn |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(3) .input-group-prepend > .btn")).click();
        // 21 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click();
        // 22 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click();
        // 23 | assertText | css=tr:nth-child(4) > .ng-binding | €3.25
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText(), is("€3.25"));
        // 24 | click | css=.ng-scope:nth-child(3) .input-group-append > .btn |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(3) .input-group-append > .btn")).click();
        // 25 | assertText | css=tr:nth-child(4) > .ng-binding | €6.25
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText(), is("€6.25"));
    }
    @Test
    public void totalCarrito1() {
        // Test name: TotalCarritoColas
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("http://localhost:3000/");
        // 2 | setWindowSize | 973x1095 |
        driver.manage().window().setSize(new Dimension(973, 1095));
        // 3 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click();
        // 4 | assertText | css=tr:nth-child(4) > .ng-binding | €1.25
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText(), is("€1.25"));
        // 5 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click();
        // 6 | assertText | css=tr:nth-child(4) > .ng-binding | €2.50
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText(), is("€2.50"));
        // 7 | click | css=.ng-scope:nth-child(1) > td .input-group-prepend > .btn |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-prepend > .btn")).click();
        // 8 | click | css=.ng-scope:nth-child(1) > td .input-group-prepend > .btn |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-prepend > .btn")).click();
        // 9 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click();
        // 10 | assertText | css=tr:nth-child(4) > .ng-binding | €2.00
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText(), is("€2.00"));
        // 11 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click();
        // 12 | assertText | css=tr:nth-child(4) > .ng-binding | €4.00
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText(), is("€4.00"));
        // 13 | click | css=.ng-scope:nth-child(2) > td .input-group-prepend > .btn |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-prepend > .btn")).click();
        // 14 | click | css=.ng-scope:nth-child(2) > td .input-group-prepend > .btn |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-prepend > .btn")).click();
        // 15 | click | css=.ng-scope:nth-child(3) .input-group-append > .btn |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(3) .input-group-append > .btn")).click();
        // 16 | assertText | css=tr:nth-child(4) > .ng-binding | €3.00
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText(), is("€3.00"));
        // 17 | click | css=.ng-scope:nth-child(3) .input-group-append > .btn |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(3) .input-group-append > .btn")).click();
        // 18 | assertText | css=tr:nth-child(4) > .ng-binding | €6.00
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText(), is("€6.00"));
        // 19 | click | css=.ng-scope:nth-child(3) .input-group-prepend > .btn |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(3) .input-group-prepend > .btn")).click();
        // 20 | click | css=.ng-scope:nth-child(3) .input-group-prepend > .btn |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(3) .input-group-prepend > .btn")).click();
        // 21 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click();
        // 22 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click();
        // 23 | assertText | css=tr:nth-child(4) > .ng-binding | €3.25
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText(), is("€3.25"));
        // 24 | click | css=.ng-scope:nth-child(3) .input-group-append > .btn |
        driver.findElement(By.cssSelector(".ng-scope:nth-child(3) .input-group-append > .btn")).click();
        // 25 | assertText | css=tr:nth-child(4) > .ng-binding | €6.25
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText(), is("€6.25"));
    }
}