package com.sinensia.hellorobobartesting.pageobject;// Generated by Selenium IDE

import org.junit.jupiter.api.*;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.junit.jupiter.api.Assertions.assertEquals;

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class CartSuiteTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    CartPage cartPage;

    @BeforeAll
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @BeforeEach
    public void setupTest() {
        cartPage = new CartPage(driver);
        driver.get("http://localhost:3000/");
    }

    @AfterAll
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void colaTest() {
        // Add o cola
        cartPage.addColaButton.click();
        // Total must be €1.25
        assertEquals(cartPage.totalField.getText(), "€1.25");
        // Add o cola
        cartPage.addColaButton.click();
        // Total must be €2.50
        assertEquals(cartPage.totalField.getText(), "€2.50");
    }

    @Test
    public void beerTest() {
        cartPage.addBeerButton.click();
        assertEquals(cartPage.totalField.getText(), "€2.00");
        cartPage.addBeerButton.click();
        assertEquals(cartPage.totalField.getText(), "€4.00");
    }

    @Test
    public void wineTest() {
        cartPage.addWineButton.click();
        assertEquals(cartPage.totalField.getText(), "€3.00");
        cartPage.addWineButton.click();
        assertEquals(cartPage.totalField.getText(), "€6.00");
    }

}
